[package]
name = "awsaml"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", tag = "1.0.15", features = [
  "fetch",
] }
